# Generated by Django 5.0 on 2023-12-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product_quantity', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
