# Generated by Django 5.0 on 2023-12-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_purchase_purchaseitem_purchase_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
