# Generated by Django 5.0 on 2023-12-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customers',
            managers=[
            ],
        ),
    ]
